### ISSUE TITLE
Symbols / Source code not showing in MinGW 64 application

### ISSUE THREAD

**Issue by RandomGuy252** [milostosic/MTuner#55]
I have tried to debug a minGW 64 (7.3.0) application to have an idea where memory is more allocated but for some reason the source code does not show up:

![image](https://user-images.githubusercontent.com/62431000/77166394-7eaac600-6ab4-11ea-85e1-e98958dd1215.png)

I compiled the application with minGW and debug symbols activated (DWARF information), using the flags (qmake):
QMAKE_CXXFLAGS += -gdwarf-2
CONFIG += force_debug_info

This works correctly for VTune, but for MTuner for some reason does not seem to work.

I have also setup the MinGW toolchain and it looks like this:

![image](https://user-images.githubusercontent.com/62431000/77166268-3ab7c100-6ab4-11ea-9746-f565caf7b8ff.png)

I am not sure what I am missing or doing wrong.

Can you give some help, most of the issues here are for VC++ so not helpful for minGW.

P.S. I am using a release executable (-O2), MTuner version is 4.3.5, the MinGW toolchain is the one that comes with Qt 5.12.3.

**Comment by anna-prog81** [comment]
+1. Does any version of MTuner work with MinGW and what compiler flags need to be set for showing source code?

**Comment by milostosic** [comment]
I'll check this problem these days, quite busy with my regular job.

**Comment by milostosic** [comment]
Took me a while but I see the problem which is a design flaw. I assume you are drag & dropping executables to MTuner or running them from project manager? If this is the case then a profile DLL is injected and this DLL was compiled with MSVC so the toolchain saved in the capture file is wrongly saved as MSVC and debug symbol resolver doesn't work. 

The real solution to this problem would be to detect the type of executable being profiled by inspecting PE header or something. I'll take a look at what would be an easy way for this.

**Comment by RandomGuy252** [comment]
> I assume you are drag & dropping executables to MTuner or running them from project manager?

Yes that's how I am doing it.

**Comment by anna-prog81** [comment]
And I too. Even without source code - it's a great instrument. I learned a lot about my program). I am looking forward for update with source code inspection.

**Comment by milostosic** [comment]
I'll try to fix this over the next weekend. It's more involved than I thought - right now a single toolchain is assumed for all modules on Windows, which is obviously wrong as exe could be compiled with MinGW while DLLs could be built with MSVC. So I want to rewrite this part a bit so the symbols can be loaded regardless of how the module was compiled... a bit of patience please, quite swarmed with other work.

**Comment by milostosic** [comment]
Just submitted the fix. Debug symbols are now handled/loaded per module, which allows .exe and .dll files to be resolved using appropriate toolchain for each module. Tested with a MinGW compiled binary and I could see symbols both from it and from system DLLs (which were compiled with MSVC) in a call stack. I'll post a new release later today.

**Comment by RandomGuy252** [comment]
That is great! Let us know once you release it. I will test it ASAP.

**Comment by milostosic** [comment]
Uploaded, it's 4.3.7. Just tested with a mix of binaries (MSVC/MinGW) and it worked fine. Let me know if you find other issues. Cheers!

**Comment by RandomGuy252** [comment]
I tried the version 4.3.9 but something is not right:

![image](https://user-images.githubusercontent.com/62431000/80021246-83f79800-84da-11ea-8a4b-c831aa2f0661.png)

Toolchain is configured as in the first post.

**Comment by milostosic** [comment]
Just tested with an old capture, and got the same error. The reason is wrongly parsed output in case of a missing original executable. Is this the case for you as well?

**Comment by milostosic** [comment]
Should be fixed in v4.4.0

**Comment by RandomGuy252** [comment]
@milostosic 

I tried the 4.4.0 but the issue is still present.

**Comment by milostosic** [comment]
Do you mind trying 4.4.1? If the problem persists, please tell me how you capture the profile as I cannot reproduce it locally.

**Comment by RandomGuy252** [comment]
Still doesn't work. How did you compiled your test application? Did you used -gdwarf-2?

For the capture I just go to projects then I click in "run", then I terminate the application normally to analyse the results.

![image](https://user-images.githubusercontent.com/62431000/80225358-41090200-864b-11ea-8621-e2aea86ad623.png)

For the binutils path I am using:
D:/Qt512x64/Tools/mingw730_64/bin

**Comment by milostosic** [comment]
My test was compiled with '-g'. I will try to make a test with -gdwarf-2 and see if there is any difference in terms of addr2line output.

**Comment by RandomGuy252** [comment]
Odd I tried with just -g but it does not matter same issue. :/

**Comment by milostosic** [comment]
My guess is that the addr2line output format is different and that parsing is incorrect, I'll need to try the same version of compiler that you use in order to check this.

**Comment by milostosic** [comment]
I just tried with [x86_64-7.3.0-release-win32-sjlj-rt_v5-rev0.7z](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.3.0/threads-win32/sjlj/x86_64-7.3.0-release-win32-sjlj-rt_v5-rev0.7z/download) and everything is working fine. I'll try to install Qt512 so the toolchain I use is identical to yours but help me out here - can you think of anything else that could make yours and mine configurations different?

**Comment by milostosic** [comment]
Which exact version of Qt/MinGW did you install? There's a number of sub versions: http://download.qt.io/archive/qt/5.12/

**Comment by RandomGuy252** [comment]
I used Qt 5.12.3 x64.

**Comment by milostosic** [comment]
Ok, I've just tested with MinGW 7.4 included with Qt 5.12.3 and everything works fine.
I can only assume something is incorrectly setup on your PC.
You can send over a minimal repro case so I can take a look, otherwise I'm closing this issue.

**Comment by RandomGuy252** [comment]
MinGW should be 7.3 with that version.

Can you tell how you did configure the toolchain?

Mine looks like this:

![image](https://user-images.githubusercontent.com/62431000/80309298-886eca00-87d4-11ea-9532-3eaed7cd9c8c.png)

Enviroment variable: MINGW64
Binutils path: D:/Qt512x64/Tools/mingw730_64/bin
Toolchain prefix: (I left empty)

Minimum reproducible project (in my scenario):
[cpp_tests.zip](https://github.com/milostosic/MTuner/files/4535431/cpp_tests.zip)

**Comment by milostosic** [comment]
Yes, it was 7.3, I made a typo. Here's my setup, I use TDM-GCC:
![image](https://user-images.githubusercontent.com/1654399/80310063-5036ae00-880b-11ea-89cd-8fb050028cbd.png)
I don't use Qt creator so if you can generate a makefile with this .pro project please send that over.

**Comment by RandomGuy252** [comment]
Makefile:
[Makefile.zip](https://github.com/milostosic/MTuner/files/4535478/Makefile.zip)

Btw I do not have the environment variable "MINGW64" setup in the system. Can be that the problem?

**Comment by milostosic** [comment]
I'll try this in the morning, time to sleep here. MINGW64 not being set in the system is not a problem.

**Comment by milostosic** [comment]
From your makefile:
-Wl,**-s** -Wl,-subsystem,console -mthreads
Debug symbols are explicitly removed.

**Comment by RandomGuy252** [comment]
I removed the -s argument (which I was not aware of), but the problem remains.

It must be something else, I completely discard the compilation with make file and now I am compiling it directly like this:
D:/Qt512x64/Tools/mingw730_64/bin/g++ -g main.cpp -o app.exe

But I get the same issue when I try MTuner.

**Comment by milostosic** [comment]
Check if you actually have debug symbols:
    objdump --syms app.exe 

Anyway, I've wasted too much time on this already but whatever I tried it always worked fine: different MinGW versions, different build process, etc. Unless someone can provide an actual repro case I will not be looking into it further.

**Comment by RandomGuy252** [comment]
I checked with objdump and the symbols are in the executable.

I will leave the executable here anyway, if somebody wants to test:
[app.zip](https://github.com/milostosic/MTuner/files/4538958/app.zip)

@anna-prog81 Is it working for you already?

**Comment by milostosic** [comment]
I tested your executable with 4.4.1 - working fine:
![image](https://user-images.githubusercontent.com/1654399/80374712-ae29cb00-88c9-11ea-8aa5-223cc7f856f0.png)

**Comment by anna-prog81** [comment]
I tested my application with 4.4.1. Compiled with '-g'. Now I can see source code lines, but only in my executable, not dlls. A lot of "Unknown", "fake" entries.  I see all my dlls in Modules window, filtering by modules works. MinGW 4.4 +Qt 4.8.5,  MinGW 4.9.2 + Qt 5.6.3.
![изображение](https://user-images.githubusercontent.com/62877902/80530293-75f5bb80-89a1-11ea-80e3-7383612a61df.png)
![изображение](https://user-images.githubusercontent.com/62877902/80530356-8e65d600-89a1-11ea-8e60-ba38d2d63b39.png)

**Comment by milostosic** [comment]
Ok, I'll take another look at this...

**Comment by Banderi** [comment]
I feel bad resurfacing this closed issue, but I just can't seem to get it to work on my end.
I tried with multiple mingw versions, different compiler settings, nothing works. I even tried to convert it to .pdb and stripping the exe of debug symbols.
Here's my exe (will close upon hitting "cancel"):
[cmake-build-debug.zip](https://github.com/milostosic/MTuner/files/8404820/cmake-build-debug.zip)
[cmake-build-release.zip](https://github.com/milostosic/MTuner/files/8404821/cmake-build-release.zip)
[cmake-build-relwithdebinfo.zip](https://github.com/milostosic/MTuner/files/8404822/cmake-build-relwithdebinfo.zip)
